name: test
channels:
  - defaults
dependencies:
  - python=3.9.19
  - pip
  - pip:
    - bidict==0.23.1
    - cvxopt==1.3.2
    - lxml==5.2.2
    - numba==0.60.0
    - numpy==2.0.0
    - pandas==2.2.2
    - PySide6==6.7.2
    - PySide6_Addons==6.7.2
    - PySide6_Essentials==6.7.2
    - PySide6_Fluent_Widgets==1.5.8
    - pyteomics==4.7.2
    - scikit_learn==1.5.1
    - scipy==1.13.1
    - setuptools==69.5.1
    - statsmodels==0.14.2
